### ISSUE TITLE
Criação da Seção do To-do list

### ISSUE THREAD

**Issue by JoaoVictorViana** [JoaoVictorViana/coopers-app#7]
Critério de aceite:

**Eu como** usuário **preciso acessar o sistema** e seção do To-do list seguindo o [Layout](https://www.figma.com/file/OAMrciHo0uOf4H2cgg3MDm/Coopers---Site-para-teste-Front-End-%2F-Full-Stack?node-id=290-6334&t=3JrGufy5pdhvlxFH-0).

**Eu como** usuário também **preciso criar, editar, excluir e mover** cada item do to-do list. Cada item do to-do list que for concluida, será movida para o card "Done". Também será necessário ter um **botão para deletar** todos os items da listagem

O Layout precisa ser responsivo (utilizando **Mobile First**), ou seja, ser possível acessar tanto pelo celular, tablet ou computador. Também é necessário seguir as regras de compatibilidade entre navegadores.

- [x] Card do To-do List
- [x] CRUD de items
- [x] Drag-and-drop
- [x] Botão de deletar todos (Erease all)
- [x] Card Done
